# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

blockpfGaussianOpt_impl <- function(data, part, lag) {
    .Call(`_RcppSMC_blockpfGaussianOpt_impl`, data, part, lag)
}

LinReg_impl <- function(Data, lNumber) {
    .Call(`_RcppSMC_LinReg_impl`, Data, lNumber)
}

LinRegLA_impl <- function(Data, intemps, lNumber) {
    .Call(`_RcppSMC_LinRegLA_impl`, Data, intemps, lNumber)
}

LinRegLA_adapt_impl <- function(Data, lNumber, resampTol, tempTol) {
    .Call(`_RcppSMC_LinRegLA_adapt_impl`, Data, lNumber, resampTol, tempTol)
}

nonLinPMMH_impl <- function(data, lNumber, lMCMCits) {
    .Call(`_RcppSMC_nonLinPMMH_impl`, data, lNumber, lMCMCits)
}

pfLineartBS_impl <- function(data, part, usef, fun) {
    .Call(`_RcppSMC_pfLineartBS_impl`, data, part, usef, fun)
}

pfNonlinBS_impl <- function(data, part) {
    .Call(`_RcppSMC_pfNonlinBS_impl`, data, part)
}

